#!/bin/sh

if ! uci -q get uhttpd.net4sats >/dev/null 2>&1; then
    uci set uhttpd.net4sats=uhttpd
    uci set uhttpd.net4sats.home='/www/net4sats'
    uci set uhttpd.net4sats.ubus_prefix='/ubus'
    uci set uhttpd.net4sats.script_timeout='60'
    uci set uhttpd.net4sats.network_timeout='30'
    uci set uhttpd.net4sats.max_requests='3'
    uci set uhttpd.net4sats.tcp_keepalive='1'
    uci set uhttpd.net4sats.error_page='/index.html'
    uci add_list uhttpd.net4sats.listen_http='0.0.0.0:80'
    uci add_list uhttpd.net4sats.listen_http='[::]:80'
    uci commit uhttpd
fi

/etc/init.d/rpcd restart
/etc/init.d/uhttpd restart
/etc/init.d/nodogsplash restart 2>/dev/null || true

touch /etc/configurationwizzard-setup-done
exit 0
